project_id = "hxvjibdsldkvnaccfgah"

[functions.chat]
verify_jwt = false

[functions.webhook-integration]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generar-fichas]
verify_jwt = true

[functions.update-invited-user]
verify_jwt = false

[functions.generate-media]
verify_jwt = false

[functions.get-starter-profile]
verify_jwt = false

[functions.get-system-prompt]
verify_jwt = false

[functions.upload-to-s3]
verify_jwt = false

[functions.daily-reports]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.query-knowledge]
verify_jwt = false
