project_id = "hxvjibdsldkvnaccfgah"

[functions.chat]
verify_jwt = false

[functions.webhook-integration]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.generar-fichas]
verify_jwt = true

[functions.update-invited-user]
verify_jwt = false
